In [49]:
import json
from math import log
import pandas as pd

def preprocess(line, sep):
    data = json.loads(line)
    if data['salary'][sep] is not None:
        res = f"{log(float(data['salary'][sep]))} "
    else:
        return 0
    res += f"|billing_type {data['billing_type']['id']}"
    res += f"|accept_handicapped {data['accept_handicapped']}"
    if data['key_skills']:
        res += '|key_skills '
        for elem in data['key_skills']:
            res += f"{elem['name'].encode('utf8').decode().replace(' ', '_').replace(':', '')} "
        
    res += f"|employment {data['employment']['id']}"
    res += f"|archived {data['archived']}"
    if 'id' in data['employer']:
        res += f"|employer {data['employer']['id']}"
    res += f"|response_letter_required {data['response_letter_required']}"
    res += f"|type {data['type']['id']}"
    if data['specializations']:
        res += '|specializations '
        for elem in data['specializations']:
            res += f"{elem['id']} "
    res += f"|premium {data['premium']}"
    res += f"|schedule {data['schedule']['id']}"
    res += f"|billing_type {data['billing_type']['id']}"
    if data['department']:
        res += f"|department {data['department']['id']}"
    if data['address']:
        if 'city' in data:
            res += f"|address {data['address']['city'].encode('utf8').replace(':', '')}"
    res += '|name ' + data['name'].encode('utf8').decode().replace(':', '')
    res += f"|area {data['area']['id']}"
    res += f"|experience {data['experience']['id']}"
    res += '|description ' + data['description'].encode('utf8').decode().replace(':', '').replace('\n', ' ')
    
    return res

def preprocess_test(line):
    data = json.loads(line)
    res = '0 '
    
    res = res + f"|billing_type {data['billing_type']['id']}"
    res = res + f"|accept_handicapped {data['accept_handicapped']}"
    if data['key_skills']:
        res = res + '|key_skills '
        for elem in data['key_skills']:
            res = res + f"{elem['name'].encode('utf8').decode().replace(' ', '_').replace(':', '')} "
        
    res = res + f"|employment {data['employment']['id']}"
    res = res + f"|archived {data['archived']}"
    if 'id' in data['employer']:
        res = res + f"|employer {data['employer']['id']}"
    res = res + f"|response_letter_required {data['response_letter_required']}"
    res = res + f"|type {data['type']['id']}"
    if data['specializations']:
        res = res + '|specializations '
        for elem in data['specializations']:
            res = res + f"{elem['id']} "
    res = res + f"|premium {data['premium']}"
    res = res + f"|schedule {data['schedule']['id']}"
    res = res + f"|billing_type {data['billing_type']['id']}"
    if data['department']:
        res = res + f"|department {data['department']['id']}"
    if data['address']:
        if 'city' in data:
            res = res + f"|address {data['address']['city'].encode('utf8').replace(':', '')}"
    res = res + '|name ' + data['name'].encode('utf8').decode().replace(':', '')
    res = res + f"|area {data['area']['id']}"
    res = res + f"|experience {data['experience']['id']}"
    res = res + '|description ' + data['description'].encode('utf8').decode().replace(':', '').replace('\n', ' ')
    
    return res

In [82]:
def transform_to_vw(inpt, output):
    with open(inpt, 'r') as inp, open(output, 'w') as out:
        for line in inp:
            tline = transform_json(line, 'from')
            if isinstance(tline, int):
                continue
        out.write(tline + '\n')
        print('Writing complete')

In [83]:
transform_to_vw('train.txt', 'data_low.vw')

Writing complete


In [84]:
transform_to_vw('train.txt', 'data_high.vw')

Writing complete


In [85]:
with open('data_low.vw', 'r') as f:
    for line in f.readlines(1):
        print(line)

10.126631103850338 |billing_type free|accept_handicapped False|employment full|archived True|employer 1515327|response_letter_required False|type open|specializations 20.387 |premium False|schedule fullDay|billing_type free|name Производитель работ|area 49|experience between3And6|description <p><strong>Условия</strong></p> <ul> <li>Сфера деятельности Строительство</li> <li>График работы Полный день, 5/2</li> </ul> <p> </p> <p><strong>Требуемый опыт работы </strong></p> <ul> <li>Более 3 лет, высшее образование по направлению гражданское и пром. строительство.</li> </ul> <p> </p> <p><strong>Обязанности</strong></p> <ul> <li>Организационно-распорядительные документы и нормативные материалы вышестоящих и других органов, касающиеся производственно-хозяйственной деятельности участка (объекта).</li> <li>Организацию и технологию строительного производства.</li> <li>Нормы и расценки</li> </ul>



In [53]:
!cat data_high.vw | tail -100000 >> test_high.vw
!cat data_high.vw | head -290000 >> train_high.vw

cat: stdout: Broken pipe


In [55]:
!wc data_high.vw

  390960 63057168 949264504 data_high.vw


In [56]:
!cat data_low.vw | tail -100000 >> test_low.vw
!cat data_low.vw | head -540000 >> train_low.vw

cat: stdout: Broken pipe


In [57]:
!vw -d train_low.vw -c -f model_low.vw --ftrl

final_regressor = model_low.vw
Enabling FTRL based optimization
Algorithm used: Proximal-FTRL
ftrl_alpha = 0.005
ftrl_beta = 0.1
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
creating cache_file = train_low.vw.cache
Reading datafile = train_low.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
106.951660 106.951660            1            1.0  10.3417   0.0000       75
87.880878 68.810097            2            2.0   8.5172   0.2220      153
93.990223 100.099567            4            4.0  10.8198   0.5810      207
95.530644 97.071066            8            8.0   9.7981   1.0559      116
92.893018 90.255391           16           16.0  15.7441   2.0837      218
81.520527 70.148037           32           32.0  11.2252   2.0292      111
62.562173 43.603819           64           64.0   9.7410   1.2855       72
48.582030 34.601887          128       

In [58]:
with open('train_low.vw', 'r') as f:
    for line in f.readlines(1):
        print(line)

10.341742483467284 |billing_type free|accept_handicapped False|employment full|archived False|employer 1942790|response_letter_required False|type open|specializations 3.318 3.98 3.230 3.90 |premium False|schedule fullDay|billing_type free|name Менеджер он-лайн офиса|area 1884|experience between1And3|description <p><strong>Обязанности</strong> консультирование клиентов, работа с электронной почтой, обучение новых сотрудников, ведение отчета по проделанной работе.</p> <p> </p> <p><strong>Требования</strong> уверенный пользователь ПК, скоростной интернет, целеустремленность, желание зарабатывать, терпеливость при работе с клиентами, ответственность, доброжелательность.</p> <p> </p> <p><strong>Условия</strong> трудоустройство по Т.З.Р.Ф., своевременная зарплата, бонусы, премии, бесплатное обучение и сопровождение до результата, карьерный рост.</p> <p>Обращаться по эл. почте</p>



In [59]:
!vw -d train_high.vw -c -f model_high.vw --ftrl

final_regressor = model_high.vw
Enabling FTRL based optimization
Algorithm used: Proximal-FTRL
ftrl_alpha = 0.005
ftrl_beta = 0.1
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
creating cache_file = train_high.vw.cache
Reading datafile = train_high.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
109.476509 109.476509            1            1.0  10.4631   0.0000       48
114.660633 119.844757            2            2.0  11.0021   0.0547       71
111.746721 108.832809            4            4.0  10.0432   0.5217      128
106.070099 100.393476            8            8.0  10.5966   0.2365       47
97.291622 88.513145           16           16.0  10.0858   0.9092       97
82.861560 68.431498           32           32.0  10.4043   2.9572      181
70.255918 57.650276           64           64.0  10.7144   3.7279      187
53.459390 36.662863          12

In [60]:
import numpy as np
def create_test(filename):
    t = []
    with open(filename, 'r') as f:
        for line in f:
            t.append(np.exp(float(line.split()[0])))
    return t

In [61]:
test_from = create_test('test_low.vw')

In [62]:
test_to = create_test('test_high.vw')

In [63]:
# Перекрестная тренировка моделей

!vw -t test_high.vw -i model_high.vw -p hh_model.csv
!vw -t test_high.vw -i model_low.vw -p hl_model.csv
!vw -t test_low.vw -i model_low.vw -p ll_model.csv
!vw -t test_low.vw -i model_high.vw -p lh_model.csv

only testing
predictions = hh_model.csv
Enabling FTRL based optimization
Algorithm used: Proximal-FTRL
ftrl_alpha = 0.005
ftrl_beta = 0.1
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = test_high.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.641880 0.641880            1            1.0  10.1943  10.9955      138
0.569881 0.497882            2            2.0  12.4292  11.7236      205
0.304516 0.039150            4            4.0  10.5966  10.3791      105
3.894532 7.484548            8            8.0  15.7614  10.3220       58
2.181072 0.467613           16           16.0  11.0666  10.5763      318
1.243639 0.306206           32           32.0  11.0666  10.4277      314
0.969430 0.695220           64           64.0  11.5129  11.8950      280
1.379351 1.789273          128          128.0  10.8198  10.9407      100


In [64]:
lpred_h = np.exp(pd.read_csv('lh_model.csv', header=None).values[:, 0])
lpred_l = np.exp(pd.read_csv('ll_model.csv', header=None).values[:, 0])
lpreds = (lpred_h + lpred_l)/2

hpred_h = np.exp(pd.read_csv('hh_model.csv', header=None).values[:,0])
hpred_l = np.exp(pd.read_csv('hl_model.csv', header=None).values[:,0])
hpreds = (hpred_h + hpred_l)/2

In [65]:
lpreds

array([100480.48844612,  61809.77930508,  20024.2969826 , ...,
        48958.77944551,  21110.80992078,  38702.25491747])

In [66]:
hpreds

array([ 59697.10104698, 112102.01348284,  52851.46552987, ...,
        46919.99861182, 141120.99703678,  48958.77944551])

In [78]:
def get_error():
    low_error = np.sqrt(np.mean((lpreds / test_from - 1) ** 2))
    high_error = np.sqrt(np.mean((test_to / hpreds - 1) ** 2))
    return 0.5 * low_error + 0.5 * high_error
get_error()

294.1334693830131

In [86]:
with open('test.txt', 'r') as inp, open('test.vw', 'w') as out:
    for line in inp:
        tline = preprocess_test(line, )
        data = json.loads(line)
        if isinstance(tline, int):
            continue
        out.write(tline + '\n')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [70]:
# Прогон тестовой выборки по тренированным моделям

!vw -t test.vw -i model_high.vw -p test_high.csv
!vw -t test.vw -i model_low.vw -p test_low.csv

only testing
predictions = test_high.csv
Enabling FTRL based optimization
Algorithm used: Proximal-FTRL
ftrl_alpha = 0.005
ftrl_beta = 0.1
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
109.364822 109.364822            1            1.0   0.0000  10.4578      200
102.390083 95.415344            2            2.0   0.0000   9.7681       75
108.674677 114.959270            4            4.0   0.0000  10.2721      114
106.227323 103.779968            8            8.0   0.0000   9.9055      125
100.936146 95.644969           16           16.0   0.0000   7.8486       69
97.379865 93.823585           32           32.0   0.0000  11.6924      179
102.966103 108.552341           64           64.0   0.0000   9.4443      335
106.988884 111.011664          128          128.0   0

In [74]:
def get_test_preds():
    hpreds_tst = np.exp(pd.read_csv('test_high.csv', header=None).values[:,0])
    lpreds_tst = np.exp(pd.read_csv('test_low.csv', header=None).values[:,0])

    return 0.5 * lpreds_tst + 0.5 * hpreds_tst

In [76]:
get_test_preds()

array([31367.57059494, 18515.77304107, 70197.15323984, ...,
       55168.07560602, 14399.92400044, 73244.69414034])